name: Deploy new version

# Only deploy when a new tag is pushed
on:
  push:
    tags:
      - "v*.*.*"


# Must match the project() name in CMakeLists.txt
env:
  APP_NAME: app


# Allow this workflow to write back to the repository
permissions:
  contents: write

# Build binary and send to releases
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:

      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t cpp-template-image -f Dockerfile .

      - name: Create Docker container
        run: docker create --name cpp-template-container cpp-template-image 

      - name: Copy out app binary file
        run: docker cp cpp-template-container:/project/build/${APP_NAME} ./${APP_NAME}

      - name: Put environment variable into the env context
        run: echo "app_name=$APP_NAME" >> $GITHUB_ENV

      - name: Push to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.app_name }}
          body_path: CHANGELOG.md
